version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
    - 5.4.29.Final
  - dependency-name: org.hibernate:hibernate-entitymanager
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
    - 5.4.29.Final
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.2
    - 5.3.4
  - dependency-name: org.springframework:spring-webmvc
    versions:
    - 5.3.2
    - 5.3.4
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.2
    - 5.3.3
    - 5.3.4
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.2
    - 5.3.3
    - 5.3.4
  - dependency-name: org.mongodb:mongo-java-driver
    versions:
    - 3.12.7
